name: '🤖 提交助手 | Submit Agent'
description: '提交助手设定 | Submit an agent setting'
title: '[Agent] Your agent name'
labels: '🤖 Agent PR'
body:
  - type: input
    attributes:
      label: 'identifier'
      description: 'Agent identifier should be unique and written in English, Ex: web-development'
  - type: input
    attributes:
      label: 'avatar'
      description: '🤯 Emoji or Logo url'
    validations:
      required: true
  - type: input
    attributes:
      label: 'title'
      description: 'Agent en_US title, will auto generate i18n in workflow'
    validations:
      required: true
  - type: input
    attributes:
      label: 'description'
      description: 'Agent en_US description, will auto generate i18n in workflow'
    validations:
      required: true
  - type: input
    attributes:
      label: 'tags'
      description: 'Split with `,`'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'systemRole'
      description: 'You agent prompt'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 'locale'
      options:
        - en_US
        - zh_CN
    validations:
      required: true
