name: Auto Submit

on:
  issues:
    types: [labeled]

jobs:
  autoflow:
    runs-on: ubuntu-latest
    if: github.event.label.name == '🤖 Agent PR'
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: pnpm install

      - name: Auto submit
        run: pnpm run submit
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}